// import 'bootstrap/dist/css/bootstrap.min.css';

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#f5f6fa" }}>
        {children}
      </body>
    </html>
  );
}
